### ISSUE TITLE
Cannot select multiple products, models for search

### ISSUE THREAD

**Issue by sashakames** [aims-group/metagrid#239]
### Describe the bug

**Desktop (please complete the following information):**
- OS: Mac OSX
- Browser and Version: Firefox v78.6.1

#### To Reproduce

1.  select "All (exept CMIP6)" in Select a Project drop
2. open  Product selector 
3. click "select options"  eg for Project select MREAnalysis2
4. Try to type an additional product name - this doesn't appear possible.
    eg.  - you get a small "No data" popup and the cmip5 facet remains

#### Expected behavior

You should be able to add additional Products, Models etc. to the search. 

This appears to work properly with variables, so maybe just a case to enable for additional facets.

#### Additional context

Searching one project at a time is probably ok.

**Comment by sashakames** [comment]
Another issue is when a single option is selected, the user cannot see the other possible options to select because the results narrow down rather quickly.

**Comment by tomvothecoder** [comment]
> Another issue is when a single option is selected, the user cannot see the other possible options to select because the results narrow down rather quickly.

@sashakames In the initial facets filtering on CoG, you are allowed to combine options between different facets that aren't compatible and return 0 results. By auto-filtering, it eliminates options that can't be combined.

To resolve your original issue, we can use a multi-select dropdown instead of a single select dropdown. This allows users to select multiple options (OR operator) for a single facet at once, which will auto-filter down the options of the other facets. 

I originally thought I implemented a multi-select, so good catch here.

New Filtering Flow
---
1. Initially, user selects multiple options for a facetA
2. Auto-filtering is performed
3. facetA will only show the available facet options based on Search API results -- this is what you applied (same behavior as CoG)
  - If user tries to find more options for facetA, 'No Data' will appear which is expected behavior (CoG only shows checkboxes for applied options)
4. Other facets are also narrowed down for compatibility based on Search API results

**Comment by tomvothecoder** [comment]
After doing a review of the code, the dropdown is already configured as `mode='multiple'`. 

The root cause of this issue is actually the `onChange` function, which captures whenever form values change. By clicking one option under it facet, it triggers a 'change' event which performs the auto-filtering. As a result, users can't click multiple options.

I need to find a way for auto-filtering to be performed after the dropdown **closes**, not when a single option is selected.

**Comment by sashakames** [comment]
It might be out of scope but one idea would be to have something like "add additional values" and that value list could be populated from a cached set of facet values prior to the filtering by the initial set of values. 
simple example:  I have selected a experiment (historical), now need to select the variables of interest.  I select one (eg ta) and wait, then realize I want more.  I have the option to bring back the list because the last full list of variables from the search with historical was saved.
more complicated.  Now I want to add an additional experiment.  If we go back to the original list and I happen to select an experiment that doesn't match with the selected variables, I'm stuck with the empty-set situation that was pointed out with CoG.
